### ISSUE TITLE
Compilation warnings/error with msvc

### ISSUE THREAD

**Issue by ggaudeau** [groundswellaudio/swl-variant#7]
I run into compilation problems when I build with msvc++ 19.44.35207.1:
```
include\swl\variant_detail.hpp(228,24): warning C4244: 'return': conversion from 'unsigned int' to 'unsigned char', possible loss of data
include\swl\variant_detail.hpp(330,15): error C2039: 'address_of': is not a member of 'std'
include\swl\variant.hpp(844,77): warning C4245: 'return': conversion from 'int' to 'size_t', signed/unsigned mismatch
include\swl\variant.hpp(160,37): warning C4245: 'initializing': conversion from 'int' to 'const unsigned char', signed/unsigned mismatch
```
