### ISSUE TITLE
Compilation error with gcc

### ISSUE THREAD

**Issue by ggaudeau** [groundswellaudio/swl-variant#8]
I run into compilation problems when I build with gcc 14.2.0:
```
./include/swl/variant.hpp: In member function ‘constexpr void swl::variant<Ts>::emplace_no_dtor(Args&& ...)’:
./include/swl/variant.hpp:505:73: error: self-comparison always evaluates to true [-Werror=tautological-compare]
  505 |                                 static_assert( can_be_valueless && (Idx == Idx),
      |                                                                     ~~~~^~~~~~
```
